config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static_pages#home'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'





  resources :gossips
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { in: 3..14 }
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def welcome
        @gossips = Gossip.all
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])  
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(title: params['title'], content: params['content'], user_id: User.all.sample.id)
    @gossip.user = User.find_by(id: session[:user_id])

    if @gossip.save
      flash[:success] = "Potin bien créé !"
      redirect_to "/", notice: 'Gossip was successfully created.'
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    @gossip.update(gossip_params)
    redirect_to "/"

  end

  def destroy
    @gossip = Gossip.find_by([:id])
    @gossip.destroy
    redirect_to "/"
  end
  

  private

  def gossip_params
    params.require(:gossip).permit(:content, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        # cherche s'il existe un utilisateur en base avec l’e-mail
        @user = User.find_by(email: params['email'])
      
        # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
        if @user && @user.authenticate(params['password'])
          session[:user_id] = @user.id
          redirect_to "/", notice: 'User was successfully created.'
          # redirige où tu veux, avec un flash ou pas
      
        else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
        end
      end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
       redirect_to "/"
    end
      
      
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @random_name = Faker::Superhero.power
    "#{@random_name}"

    @gossips = Gossip.all
  end

  
  def team
  end

  def contact
  end

  def gossip
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.all
    end

    def show
        @user = Gossip.find_by(params[:id]) 
    end

    def new
        @user = User.new
    end

    def create
        user = User.create(email: params['email'], password: params['password'])
      
        if user.save
            redirect_to "/", notice: 'User was successfully created.'
          else
            render 'new'
          end
        end

    def destroy
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to "/"
    end


        private

  def user_params

    params.require(:user).permit(:email, :password)
  end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<h1>Editer l'article</h1>

<%= form_for @gossip do |f| %>

    <div class="form_group">
        <label>Titre Du Gossip</label>
        <%= f.text_field :title, class: 'form_control' %>
    </div>

    <div class="form-group">
        <label>Contenu Du Gossip</label>
        <%= f.text_area :content, class: 'form_control' %>
    </div>

    <div class="form-group">
        <button type="submit">Modifier Le Gossip</button>
    </div>

<% end %>

app/views/gossips/index.html.erb
<Br><br><br>
<div style="text-align: center;">
    <h1>Voici la listes des Potins</h1>
  
  <% @gossips.each do |gossip| %>
<br><br>

       <div class= "container-fluid">
        <div class="row">
          <div class="col-sm">
            <h2><%= gossip.title %></h2>
            <p><%= gossip.content %></p>
            <p><a class="btn btn-primary" href="<%= gossip_path(gossip.id)%>" class="btn">Lire Le Potin &raquo;</a></p>
            <p><a class="btn btn-secondary" href="<%= new_gossip_path %>" class="btn">Modifier Le Potin</a></p>
            <p><form action="/gossips/:id" method="delete"></a><input type="submit" value="Supprimer"></p>
          </div>
        </div>


      </div> <!-- /container -->


    <% end %>

</div>

app/views/gossips/new.html.erb
<div style="text-align: center;">
  
  <br><br><br>
  <h1>Voici La Page De Création De Nouveau Potin</h1>
  <br><br><br>

  <%= form_tag('/gossips', method: 'post') do %>


    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

    <h2>Ecrivez Ici Le Titre</h2>
    <input type="text" name="title"><br><br>

    <h2>Ecrivez Ici Votre Potin</h2>
    <input type="text" name="content"><br><br>


    <button type="submit" value="Enregistrer">


  <% end %>
</div>

app/views/gossips/show.html.erb
<div style="text-align: center;">

<br><br><br><h1>Ici Doit Apparaitre Un Gossip Unique</h1>



<h1><%= @gossip.title%></h1>

<p><%= @gossip.content%></p>


<p>
    <a class="btn btn-primary" href="<%= "/gossips" %>" class="btn btn-primary">Revenir aux Gossips</a>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
  </head>

  <body>

 <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">&nbsp&nbsp&nbsp The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/gossips"> La Liste Des Potins</a>
          <li class="nav-item active">
            <a class="nav-link" href="/gossips/new"> Créer Un Nouveau Potin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/team">La Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="/users/new">Inscription</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="/sessions/new">Connexion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="/session/:id">Déconnexion</a>
          </li>
        </div>

    </nav>
    <%= yield %>
  </body>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>



</html>

app/views/static_pages/contact.html.erb
<h3>Page de contact</h3>
<p>Tu peux lacher ton 06....</p>

app/views/static_pages/home.html.erb
<div style="text-align: center;">
  <br><br><br>
  <h1> <big><big><big><big> THE GOSSIP PROJECT </big></big></big></big> </h1>
  <h2> Bienvenue sur notre site trop cool</h2>
  <br><h4>Vous avez gagné un Super Pouvoir :    <u><%= @random_name %></u></h4></div>
  <br><br><br>
</div>
<%# 
 <tbody>
 <% @gossips.each do |gossip| %>



  </tbody>

app/views/static_pages/team.html.erb
<h1>C'est la page de la Team</h1>
<p>C'est de la bombe bébé</p>

app/views/users/index.html.erb
<div style="text-align: center;">
<br><br><br>
<h1>Voici La Page Pour Créer Ta Session</h1>
<br><br><br>

<%= form_tag model: @user do |form| %>

<form action="/users_path" method="POST">
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

    <h2>Ecrivez Ici Votre Email</h2>
  <input type="text" name="email"><br><br>
    <h2>Ecrivez Ici Votre Password</h2>
  <input type="text" name="password"><br><br>






  <input type="submit" value="Enregistrer">

</form>
<% end %>
</div>

app/views/users/new.html.erb
<div style="text-align: center;">
<br><br><br>
<h1>Voici La Page Pour Créer Ton Compte</h1>
<br><br><br>

<%= form_tag model: @user do |form| %>

<form action="/users_path" method="POST">
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

    <h2>Ecrivez Ici Votre Email</h2>
  <input type="text" name="email"><br><br>
    <h2>Ecrivez Ici Votre Password</h2>
  <input type="text" name="password"><br><br>






  <input type="submit" value="Enregistrer">

</form>
<% end %>
</div>